### ISSUE TITLE
Alternative port

### ISSUE THREAD

**Issue by ncannasse** [azrafe7/hxClipper#2]
Hi,

We just noticed your Clipper Haxe port, just wanted to tell you that we also have worked on another port with some optimizations regarding allocations, which is available as part of the Heaps library there:

https://github.com/ncannasse/heaps/tree/master/hxd/clipper

It might be nice if we combine our mutual efforts to get one long-term maintained library.

Best,
Nicolas

**Comment by azrafe7** [comment]
Hi @ncannasse,
I agree with you, and I'm interested in collaborating to make a semi-official port of the lib.

I'll probably have little to no time to work on it until the end of the month, though. 

Anyway, before merging your optimizations into this codebase I'd like to do a couple of things first:
- update the code to reflect Angus' latest commits/bug fixes (he is at [r496](https://sourceforge.net/p/polyclipping/code/496/log/), while this is at r493)
- find a workable solution for Int64/128 support (not yet sure how, but probably's worth taking a look at thx and hxbitcoin)

Also, if you haven't yet, can you please test this lib by plugging it where you were previously using the heaps implementation and see if there are any obvious issues with it?

**Comment by ncannasse** [comment]
One of the change we made is to use an Int32 instead of Int64. That reduces the precision but really improve the performances since many Haxe platforms don't have native Int64 support

**Comment by azrafe7** [comment]
Hey @ncannasse, I've finally updated the project to be in line with latest _cs-useful_ Angus' revision (r498). 

If you're still interested, can you please take a deeper look and test it with your use case?
Feedback on any issues, and guidance on how to improve this are really welcomed!

I'd add that it seems that Angus has started to work on a [new version of Clipper](https://sourceforge.net/p/polyclipping/discussion/1148419/thread/be26987e/) that aims to be faster and easier to maintain (but is still in its early stages).

**Comment by azrafe7** [comment]
PS: I'm not using Int64 anywhere (that part is hidden behind a non working conditional (`USE_INT64`)). I've managed to make it almost work at some point using BigInt or hxBitcoin, but the performance was not that great (not great with that libs/defines, but the rest is all right!)

**Comment by azrafe7** [comment]
@ncannasse, fine if you don't need this lib anymore, but please reply! ;D
